package data.hullmods;

import com.fs.starfarer.api.Global;
import java.util.HashMap;
import java.util.Map;

import com.fs.starfarer.api.combat.BaseHullMod;
import com.fs.starfarer.api.combat.MutableShipStatsAPI;
import com.fs.starfarer.api.combat.ShipAPI;
import com.fs.starfarer.api.combat.ShipAPI.HullSize;
import com.fs.starfarer.api.ui.Alignment;
import com.fs.starfarer.api.ui.TooltipMakerAPI;
import com.fs.starfarer.api.util.Misc;

@SuppressWarnings("unchecked")
public class FluxDistributor extends BaseHullMod {
	
	public static float FLUX_COST_MULT = .95f;

	private static Map smag = new HashMap();
	private static Map mag = new HashMap();
	static {
		smag.put(HullSize.FRIGATE, 45f);
		smag.put(HullSize.DESTROYER, 90f);
		smag.put(HullSize.CRUISER, 130f);
		smag.put(HullSize.CAPITAL_SHIP, 200f);
		mag.put(HullSize.FRIGATE, 30f);
		mag.put(HullSize.DESTROYER, 60f);
		mag.put(HullSize.CRUISER, 90f);
		mag.put(HullSize.CAPITAL_SHIP, 150f);
	}
	
	public void applyEffectsBeforeShipCreation(HullSize hullSize, MutableShipStatsAPI stats, String id) {
		if (stats.getVariant().getSMods().contains("fluxdistributor") || stats.getVariant().getSModdedBuiltIns().contains("fluxdistributor")) {
			stats.getEnergyWeaponFluxCostMod().modifyMult(id, FLUX_COST_MULT);
			stats.getBallisticWeaponFluxCostMod().modifyMult(id, FLUX_COST_MULT);
			stats.getMissileWeaponFluxCostMod().modifyMult(id, FLUX_COST_MULT);
			stats.getFluxDissipation().modifyFlat(id, (Float) smag.get(hullSize));
		} else {
			stats.getFluxDissipation().modifyFlat(id, (Float) mag.get(hullSize));
		}
	}
	
	public String getDescriptionParam(int index, HullSize hullSize) {
		if (index == 0) return "" + ((Float) mag.get(HullSize.FRIGATE)).intValue();
		if (index == 1) return "" + ((Float) mag.get(HullSize.DESTROYER)).intValue();
		if (index == 2) return "" + ((Float) mag.get(HullSize.CRUISER)).intValue();
		if (index == 3) return "" + ((Float) mag.get(HullSize.CAPITAL_SHIP)).intValue();
		return null;
	}

    public void addPostDescriptionSection(TooltipMakerAPI tooltip, ShipAPI.HullSize hullSize, ShipAPI ship, float width, boolean isForModSpec) {
		if (isForModSpec) {
			tooltip.addSectionHeading("S-mod bonus", Misc.getGrayColor(), Misc.setAlpha(Misc.scaleColorOnly(Misc.getGrayColor(), 0.4f), 175), Alignment.MID, 10f);
			tooltip.addPara("Increases the ship's flux dissipation by an additional %s/%s/%s/%s, based on hull size.", 10f, Misc.getGrayColor(), Misc.getHighlightColor(), "15", "30", "40", "50");
			tooltip.addPara("%s flux generated by energy, ballistic, and missiles weapons", 10f, Misc.getGrayColor(), Misc.getHighlightColor(), "-5" + "%");
			return;
		} else if (ship.getVariant().getSMods().contains("fluxdistributor") || ship.getVariant().getSModdedBuiltIns().contains("fluxdistributor")) {
			tooltip.addSectionHeading("S-mod bonus", Misc.getStoryOptionColor(), Misc.getStoryDarkColor(), Alignment.MID, 10f);
			tooltip.addPara("Increases the ship's flux dissipation by an additional %s/%s/%s/%s, based on hull size.", 10f, Misc.getPositiveHighlightColor(), Misc.getHighlightColor(), "15", "30", "40", "50");
			tooltip.addPara("%s flux generated by energy, ballistic, and missiles weapons", 10f, Misc.getPositiveHighlightColor(), Misc.getHighlightColor(), "-5" + "%");
		} else if (!isForModSpec) {
			tooltip.addSectionHeading("S-mod bonus", Misc.getGrayColor(), Misc.setAlpha(Misc.scaleColorOnly(Misc.getGrayColor(), 0.4f), 175), Alignment.MID, 10f);
			tooltip.addPara("Increases the ship's flux dissipation by an additional %s/%s/%s/%s, based on hull size.", 10f, Misc.getGrayColor(), Misc.getHighlightColor(), "15", "30", "40", "50");
			tooltip.addPara("%s flux generated by energy, ballistic, and missiles weapons", 10f, Misc.getGrayColor(), Misc.getHighlightColor(), "-5" + "%");
		}
    }

}
